name: rest_api_impl
description: "A Dart package providing a robust REST API IMPL service implementation with HTTP request handling, CRUD operations, and file management."
version: 0.0.6
homepage: https://github.com/GenieCoderSrc/rest_api_impl
repository: https://github.com/GenieCoderSrc/rest_api_impl
issue_tracker: https://github.com/GenieCoderSrc/rest_api_impl/issues


environment:
  sdk: ^1.4.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  get_it_di_global_variable: ^0.0.5


  dio: ^5.8.0+1
  http: ^1.4.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  local_data_impl: ^0.0.3
  cross_file: ^0.3.4+2
  melos: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

example:
  path: example

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
